### ISSUE TITLE
I can't do anything

### ISSUE THREAD

**Issue by dragonmenorka** [gml-support/gml-support#18]
My bug is that the sprites folders, etc doesn't appear automatically.

**To Reproduce**
1. Create a .gml file.
2. See error

**Expected behavior**
All folders appear and text with colors too.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Extension Version: Last one

**Comment by LiarOnce** [comment]
Can you upload some screenshots?

**Comment by dragonmenorka** [comment]
@LiarOnce No, I can't.
