### ISSUE TITLE
无法激活扩展

### ISSUE THREAD

**Issue by NichtsVonChaos** [gml-support/gml-support#19]
**问题描述**：无法激活"GML Support"扩展，因为他依赖于未知的"robertohuertas.vscode-icons"扩展。
**VSCode版本**：x64 1.35.0
**OS**：Ubuntu 19.04 Disco with kernel "x86_64 Linux 5.0.0-16-generic"
**尝试**：找到[robertohuertasm](https://github.com/robertohuertasm)的主页，并且安装了主页的vscode-icons插件（版本8.7.0），并且在vscode中设置图标主题为"VSCode Icons"，重启vscode扔无法加载插件。

**Comment by LiarOnce** [comment]
包名被官方更换为 `	
vscode-icons-team.vscode-icons` 导致的，明天将修复这个依赖
