### ISSUE TITLE
Error message related to robertohuertasm.vscode-icons

### ISSUE THREAD

**Issue by riccicedric** [gml-support/gml-support#20]
Last version of **vscode-icons 8.7.0** by VSCode Icons Team is installed but still get the following error message :

**_Cannot activate the 'GML Support' extension because it depends on an unknown 'robertohuertasm.vscode-icons' extension ._**

**Comment by LiarOnce** [comment]
Because the extension has been changed to `
vscode-icons-team.vscode-icons` , I will fix it tomorrow.
