### ISSUE TITLE
Syntax highlighting is not behaving as expected.

### ISSUE THREAD

**Issue by JhOnNeY** [gml-support/gml-support#25]
**Describe the bug**
Syntax highlighting isn't behaving like in Gms2. 
Tried GM 8.1, GM:S, and GM:S2 syntax options and they all behave the same.

**Expected behavior**
`var` variables should be different colors than object variables.
some gms2 functions are highlighting and others are not.
some strings are being colored... others are not.

**Screenshots**
![image](https://user-images.githubusercontent.com/8714222/98727702-32ffa200-234d-11eb-8ad7-6ebecee52d50.png)

**Desktop**
 - OS: Windows 10 v19041
 - Extension Version:

**Comment by LiarOnce** [comment]
The `var` syntax has been fixed, but this project's source code is too old, I need a long time to adjust it.
![image](https://user-images.githubusercontent.com/11171892/98764952-e59c3700-2417-11eb-9893-58e1452a3fb8.png)

**Comment by JhOnNeY** [comment]
I wish I knew how to do this type of stuff, I would totally try to fix it myself.

**Comment by JhOnNeY** [comment]
how can I install the new version? VSCode shows GML Support v1.7.2

**Comment by JhOnNeY** [comment]
1.7.3 is live on VSCode Marketplace.

It is much more eye friendly now. thank you!
![image](https://user-images.githubusercontent.com/8714222/98771065-76cbc900-2398-11eb-997c-09ee2f1c298f.png)
