### ISSUE TITLE
Add toggle to disable single-quote string highlighting

### ISSUE THREAD

**Issue by PrOF-kk** [gml-support/gml-support#26]
**Is your feature request related to a problem? Please describe.**
When using object_event_add(ind, evtype, evnumb, codestr) syntax highlighting treats everything inside codestr as a string, disabling single quote string highlighting would fix this

**Describe the solution you'd like**
Add a toggle in the settings (if possible) to disable single-quote string highlighting

**Describe alternatives you've considered**
No alternatives are available

**Additional context**
![Imgur](https://imgur.com/lNckN9q.png)

**Comment by LiarOnce** [comment]
Are you using GameMaker 8 or 8.1?

**Comment by PrOF-kk** [comment]
I'm using Game Maker 8

**Comment by LiarOnce** [comment]
I have no way to add an option to do it, but I can make it compatible at the same time.
![image](https://user-images.githubusercontent.com/11171892/111025032-c7256700-841c-11eb-9c74-927e680b3e0f.png)

**Comment by PrOF-kk** [comment]
It looks exactly like what I need 👍

**Comment by PrOF-kk** [comment]
Is this supposed to be fixed in 1.7.4? It's still the same for me  
![Imgur](https://imgur.com/Hf6giN1.png)

**Comment by LiarOnce** [comment]
You may need to change the theme or clean VSCode cache to take effect.

**Comment by PrOF-kk** [comment]
I fixed it by manually changing the language in the bottom right to GameMaker Language (GameMaker 8.1), thanks again!

**Comment by LiarOnce** [comment]
I suddenly remembered that I only provided support for it under GameMaker 8.1, because it is no longer supported since GM:S1😂
